# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_handler.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x64\x61ta_handler.proto\x12\x0c\x64\x61ta_handler\"o\n\x08\x43\x61tegory\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03lft\x18\x03 \x01(\x05\x12\x0c\n\x04rght\x18\x04 \x01(\x05\x12\x0f\n\x07tree_id\x18\x05 \x01(\x05\x12\r\n\x05level\x18\x06 \x01(\x05\x12\x0e\n\x06parent\x18\x07 \x01(\x03\"\x15\n\x13\x43\x61tegoryListRequest\"%\n\x17\x43\x61tegoryRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x03\":\n\x0bMeasureUnit\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tfull_name\x18\x03 \x01(\t\"\x18\n\x16MeasureUnitListRequest\"(\n\x1aMeasureUnitRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"\xa6\x01\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x14\n\x0cproduct_type\x18\x05 \x01(\x05\x12\x10\n\x08rate_nds\x18\x06 \x01(\x02\x12\x0e\n\x06hidden\x18\x07 \x01(\x08\x12\x10\n\x08\x63\x61tegory\x18\x08 \x01(\x03\x12\x14\n\x0cmeasure_unit\x18\t \x01(\x03\"\x14\n\x12ProductListRequest\"$\n\x16ProductRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x32\x88\x04\n\nController\x12O\n\x0eListCategories\x12!.data_handler.CategoryListRequest\x1a\x16.data_handler.Category\"\x00\x30\x01\x12S\n\x10RetrieveCategory\x12%.data_handler.CategoryRetrieveRequest\x1a\x16.data_handler.Category\"\x00\x12W\n\x10ListMeasureUnits\x12$.data_handler.MeasureUnitListRequest\x1a\x19.data_handler.MeasureUnit\"\x00\x30\x01\x12\\\n\x13RetrieveMeasureUnit\x12(.data_handler.MeasureUnitRetrieveRequest\x1a\x19.data_handler.MeasureUnit\"\x00\x12K\n\x0cListProducts\x12 .data_handler.ProductListRequest\x1a\x15.data_handler.Product\"\x00\x30\x01\x12P\n\x0fRetrieveProduct\x12$.data_handler.ProductRetrieveRequest\x1a\x15.data_handler.Product\"\x00\x62\x06proto3')



_CATEGORY = DESCRIPTOR.message_types_by_name['Category']
_CATEGORYLISTREQUEST = DESCRIPTOR.message_types_by_name['CategoryListRequest']
_CATEGORYRETRIEVEREQUEST = DESCRIPTOR.message_types_by_name['CategoryRetrieveRequest']
_MEASUREUNIT = DESCRIPTOR.message_types_by_name['MeasureUnit']
_MEASUREUNITLISTREQUEST = DESCRIPTOR.message_types_by_name['MeasureUnitListRequest']
_MEASUREUNITRETRIEVEREQUEST = DESCRIPTOR.message_types_by_name['MeasureUnitRetrieveRequest']
_PRODUCT = DESCRIPTOR.message_types_by_name['Product']
_PRODUCTLISTREQUEST = DESCRIPTOR.message_types_by_name['ProductListRequest']
_PRODUCTRETRIEVEREQUEST = DESCRIPTOR.message_types_by_name['ProductRetrieveRequest']
Category = _reflection.GeneratedProtocolMessageType('Category', (_message.Message,), {
  'DESCRIPTOR' : _CATEGORY,
  '__module__' : 'data_handler_pb2'
  # @@protoc_insertion_point(class_scope:data_handler.Category)
  })
_sym_db.RegisterMessage(Category)

CategoryListRequest = _reflection.GeneratedProtocolMessageType('CategoryListRequest', (_message.Message,), {
  'DESCRIPTOR' : _CATEGORYLISTREQUEST,
  '__module__' : 'data_handler_pb2'
  # @@protoc_insertion_point(class_scope:data_handler.CategoryListRequest)
  })
_sym_db.RegisterMessage(CategoryListRequest)

CategoryRetrieveRequest = _reflection.GeneratedProtocolMessageType('CategoryRetrieveRequest', (_message.Message,), {
  'DESCRIPTOR' : _CATEGORYRETRIEVEREQUEST,
  '__module__' : 'data_handler_pb2'
  # @@protoc_insertion_point(class_scope:data_handler.CategoryRetrieveRequest)
  })
_sym_db.RegisterMessage(CategoryRetrieveRequest)

MeasureUnit = _reflection.GeneratedProtocolMessageType('MeasureUnit', (_message.Message,), {
  'DESCRIPTOR' : _MEASUREUNIT,
  '__module__' : 'data_handler_pb2'
  # @@protoc_insertion_point(class_scope:data_handler.MeasureUnit)
  })
_sym_db.RegisterMessage(MeasureUnit)

MeasureUnitListRequest = _reflection.GeneratedProtocolMessageType('MeasureUnitListRequest', (_message.Message,), {
  'DESCRIPTOR' : _MEASUREUNITLISTREQUEST,
  '__module__' : 'data_handler_pb2'
  # @@protoc_insertion_point(class_scope:data_handler.MeasureUnitListRequest)
  })
_sym_db.RegisterMessage(MeasureUnitListRequest)

MeasureUnitRetrieveRequest = _reflection.GeneratedProtocolMessageType('MeasureUnitRetrieveRequest', (_message.Message,), {
  'DESCRIPTOR' : _MEASUREUNITRETRIEVEREQUEST,
  '__module__' : 'data_handler_pb2'
  # @@protoc_insertion_point(class_scope:data_handler.MeasureUnitRetrieveRequest)
  })
_sym_db.RegisterMessage(MeasureUnitRetrieveRequest)

Product = _reflection.GeneratedProtocolMessageType('Product', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCT,
  '__module__' : 'data_handler_pb2'
  # @@protoc_insertion_point(class_scope:data_handler.Product)
  })
_sym_db.RegisterMessage(Product)

ProductListRequest = _reflection.GeneratedProtocolMessageType('ProductListRequest', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTLISTREQUEST,
  '__module__' : 'data_handler_pb2'
  # @@protoc_insertion_point(class_scope:data_handler.ProductListRequest)
  })
_sym_db.RegisterMessage(ProductListRequest)

ProductRetrieveRequest = _reflection.GeneratedProtocolMessageType('ProductRetrieveRequest', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTRETRIEVEREQUEST,
  '__module__' : 'data_handler_pb2'
  # @@protoc_insertion_point(class_scope:data_handler.ProductRetrieveRequest)
  })
_sym_db.RegisterMessage(ProductRetrieveRequest)

_CONTROLLER = DESCRIPTOR.services_by_name['Controller']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CATEGORY._serialized_start=36
  _CATEGORY._serialized_end=147
  _CATEGORYLISTREQUEST._serialized_start=149
  _CATEGORYLISTREQUEST._serialized_end=170
  _CATEGORYRETRIEVEREQUEST._serialized_start=172
  _CATEGORYRETRIEVEREQUEST._serialized_end=209
  _MEASUREUNIT._serialized_start=211
  _MEASUREUNIT._serialized_end=269
  _MEASUREUNITLISTREQUEST._serialized_start=271
  _MEASUREUNITLISTREQUEST._serialized_end=295
  _MEASUREUNITRETRIEVEREQUEST._serialized_start=297
  _MEASUREUNITRETRIEVEREQUEST._serialized_end=337
  _PRODUCT._serialized_start=340
  _PRODUCT._serialized_end=506
  _PRODUCTLISTREQUEST._serialized_start=508
  _PRODUCTLISTREQUEST._serialized_end=528
  _PRODUCTRETRIEVEREQUEST._serialized_start=530
  _PRODUCTRETRIEVEREQUEST._serialized_end=566
  _CONTROLLER._serialized_start=569
  _CONTROLLER._serialized_end=1089
# @@protoc_insertion_point(module_scope)
