# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: category.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63\x61tegory.proto\x12\x08\x63\x61tegory\x1a\x1bgoogle/protobuf/empty.proto\"o\n\x08\x43\x61tegory\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03lft\x18\x03 \x01(\x05\x12\x0c\n\x04rght\x18\x04 \x01(\x05\x12\x0f\n\x07tree_id\x18\x05 \x01(\x05\x12\r\n\x05level\x18\x06 \x01(\x05\x12\x0e\n\x06parent\x18\x07 \x01(\x03\"\x15\n\x13\x43\x61tegoryListRequest\"%\n\x17\x43\x61tegoryRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x32\x98\x01\n\x12\x43\x61tegoryController\x12=\n\x04List\x12\x1d.category.CategoryListRequest\x1a\x12.category.Category\"\x00\x30\x01\x12\x43\n\x08Retrieve\x12!.category.CategoryRetrieveRequest\x1a\x12.category.Category\"\x00\x62\x06proto3')



_CATEGORY = DESCRIPTOR.message_types_by_name['Category']
_CATEGORYLISTREQUEST = DESCRIPTOR.message_types_by_name['CategoryListRequest']
_CATEGORYRETRIEVEREQUEST = DESCRIPTOR.message_types_by_name['CategoryRetrieveRequest']
Category = _reflection.GeneratedProtocolMessageType('Category', (_message.Message,), {
  'DESCRIPTOR' : _CATEGORY,
  '__module__' : 'category_pb2'
  # @@protoc_insertion_point(class_scope:category.Category)
  })
_sym_db.RegisterMessage(Category)

CategoryListRequest = _reflection.GeneratedProtocolMessageType('CategoryListRequest', (_message.Message,), {
  'DESCRIPTOR' : _CATEGORYLISTREQUEST,
  '__module__' : 'category_pb2'
  # @@protoc_insertion_point(class_scope:category.CategoryListRequest)
  })
_sym_db.RegisterMessage(CategoryListRequest)

CategoryRetrieveRequest = _reflection.GeneratedProtocolMessageType('CategoryRetrieveRequest', (_message.Message,), {
  'DESCRIPTOR' : _CATEGORYRETRIEVEREQUEST,
  '__module__' : 'category_pb2'
  # @@protoc_insertion_point(class_scope:category.CategoryRetrieveRequest)
  })
_sym_db.RegisterMessage(CategoryRetrieveRequest)

_CATEGORYCONTROLLER = DESCRIPTOR.services_by_name['CategoryController']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CATEGORY._serialized_start=57
  _CATEGORY._serialized_end=168
  _CATEGORYLISTREQUEST._serialized_start=170
  _CATEGORYLISTREQUEST._serialized_end=191
  _CATEGORYRETRIEVEREQUEST._serialized_start=193
  _CATEGORYRETRIEVEREQUEST._serialized_end=230
  _CATEGORYCONTROLLER._serialized_start=233
  _CATEGORYCONTROLLER._serialized_end=385
# @@protoc_insertion_point(module_scope)
