# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import measure_unit_pb2 as measure__unit__pb2


class MeasureUnitControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_stream(
                '/measure_unit.MeasureUnitController/List',
                request_serializer=measure__unit__pb2.MeasureUnitListRequest.SerializeToString,
                response_deserializer=measure__unit__pb2.MeasureUnit.FromString,
                )
        self.Retrieve = channel.unary_unary(
                '/measure_unit.MeasureUnitController/Retrieve',
                request_serializer=measure__unit__pb2.MeasureUnitRetrieveRequest.SerializeToString,
                response_deserializer=measure__unit__pb2.MeasureUnit.FromString,
                )


class MeasureUnitControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MeasureUnitControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_stream_rpc_method_handler(
                    servicer.List,
                    request_deserializer=measure__unit__pb2.MeasureUnitListRequest.FromString,
                    response_serializer=measure__unit__pb2.MeasureUnit.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=measure__unit__pb2.MeasureUnitRetrieveRequest.FromString,
                    response_serializer=measure__unit__pb2.MeasureUnit.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'measure_unit.MeasureUnitController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MeasureUnitController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/measure_unit.MeasureUnitController/List',
            measure__unit__pb2.MeasureUnitListRequest.SerializeToString,
            measure__unit__pb2.MeasureUnit.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/measure_unit.MeasureUnitController/Retrieve',
            measure__unit__pb2.MeasureUnitRetrieveRequest.SerializeToString,
            measure__unit__pb2.MeasureUnit.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
