# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: measure_unit.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12measure_unit.proto\x12\x0cmeasure_unit\x1a\x1bgoogle/protobuf/empty.proto\":\n\x0bMeasureUnit\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tfull_name\x18\x03 \x01(\t\"\x18\n\x16MeasureUnitListRequest\"(\n\x1aMeasureUnitRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x32\xb7\x01\n\x15MeasureUnitController\x12K\n\x04List\x12$.measure_unit.MeasureUnitListRequest\x1a\x19.measure_unit.MeasureUnit\"\x00\x30\x01\x12Q\n\x08Retrieve\x12(.measure_unit.MeasureUnitRetrieveRequest\x1a\x19.measure_unit.MeasureUnit\"\x00\x62\x06proto3')



_MEASUREUNIT = DESCRIPTOR.message_types_by_name['MeasureUnit']
_MEASUREUNITLISTREQUEST = DESCRIPTOR.message_types_by_name['MeasureUnitListRequest']
_MEASUREUNITRETRIEVEREQUEST = DESCRIPTOR.message_types_by_name['MeasureUnitRetrieveRequest']
MeasureUnit = _reflection.GeneratedProtocolMessageType('MeasureUnit', (_message.Message,), {
  'DESCRIPTOR' : _MEASUREUNIT,
  '__module__' : 'measure_unit_pb2'
  # @@protoc_insertion_point(class_scope:measure_unit.MeasureUnit)
  })
_sym_db.RegisterMessage(MeasureUnit)

MeasureUnitListRequest = _reflection.GeneratedProtocolMessageType('MeasureUnitListRequest', (_message.Message,), {
  'DESCRIPTOR' : _MEASUREUNITLISTREQUEST,
  '__module__' : 'measure_unit_pb2'
  # @@protoc_insertion_point(class_scope:measure_unit.MeasureUnitListRequest)
  })
_sym_db.RegisterMessage(MeasureUnitListRequest)

MeasureUnitRetrieveRequest = _reflection.GeneratedProtocolMessageType('MeasureUnitRetrieveRequest', (_message.Message,), {
  'DESCRIPTOR' : _MEASUREUNITRETRIEVEREQUEST,
  '__module__' : 'measure_unit_pb2'
  # @@protoc_insertion_point(class_scope:measure_unit.MeasureUnitRetrieveRequest)
  })
_sym_db.RegisterMessage(MeasureUnitRetrieveRequest)

_MEASUREUNITCONTROLLER = DESCRIPTOR.services_by_name['MeasureUnitController']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MEASUREUNIT._serialized_start=65
  _MEASUREUNIT._serialized_end=123
  _MEASUREUNITLISTREQUEST._serialized_start=125
  _MEASUREUNITLISTREQUEST._serialized_end=149
  _MEASUREUNITRETRIEVEREQUEST._serialized_start=151
  _MEASUREUNITRETRIEVEREQUEST._serialized_end=191
  _MEASUREUNITCONTROLLER._serialized_start=194
  _MEASUREUNITCONTROLLER._serialized_end=377
# @@protoc_insertion_point(module_scope)
