# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproduct.proto\x12\x07product\x1a\x1bgoogle/protobuf/empty.proto\"\xa6\x01\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x14\n\x0cproduct_type\x18\x05 \x01(\x05\x12\x10\n\x08rate_nds\x18\x06 \x01(\x02\x12\x0e\n\x06hidden\x18\x07 \x01(\x08\x12\x10\n\x08\x63\x61tegory\x18\x08 \x01(\x03\x12\x14\n\x0cmeasure_unit\x18\t \x01(\x03\"\x14\n\x12ProductListRequest\"$\n\x16ProductRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x32\x8f\x01\n\x11ProductController\x12\x39\n\x04List\x12\x1b.product.ProductListRequest\x1a\x10.product.Product\"\x00\x30\x01\x12?\n\x08Retrieve\x12\x1f.product.ProductRetrieveRequest\x1a\x10.product.Product\"\x00\x62\x06proto3')



_PRODUCT = DESCRIPTOR.message_types_by_name['Product']
_PRODUCTLISTREQUEST = DESCRIPTOR.message_types_by_name['ProductListRequest']
_PRODUCTRETRIEVEREQUEST = DESCRIPTOR.message_types_by_name['ProductRetrieveRequest']
Product = _reflection.GeneratedProtocolMessageType('Product', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCT,
  '__module__' : 'product_pb2'
  # @@protoc_insertion_point(class_scope:product.Product)
  })
_sym_db.RegisterMessage(Product)

ProductListRequest = _reflection.GeneratedProtocolMessageType('ProductListRequest', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTLISTREQUEST,
  '__module__' : 'product_pb2'
  # @@protoc_insertion_point(class_scope:product.ProductListRequest)
  })
_sym_db.RegisterMessage(ProductListRequest)

ProductRetrieveRequest = _reflection.GeneratedProtocolMessageType('ProductRetrieveRequest', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTRETRIEVEREQUEST,
  '__module__' : 'product_pb2'
  # @@protoc_insertion_point(class_scope:product.ProductRetrieveRequest)
  })
_sym_db.RegisterMessage(ProductRetrieveRequest)

_PRODUCTCONTROLLER = DESCRIPTOR.services_by_name['ProductController']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PRODUCT._serialized_start=56
  _PRODUCT._serialized_end=222
  _PRODUCTLISTREQUEST._serialized_start=224
  _PRODUCTLISTREQUEST._serialized_end=244
  _PRODUCTRETRIEVEREQUEST._serialized_start=246
  _PRODUCTRETRIEVEREQUEST._serialized_end=282
  _PRODUCTCONTROLLER._serialized_start=285
  _PRODUCTCONTROLLER._serialized_end=428
# @@protoc_insertion_point(module_scope)
